### ISSUE TITLE
Task `test` doesn't depend on `jniCompile`

### ISSUE THREAD

**Issue by carymrobbins** [joprice/sbt-jni#13]
I'm not sure if this is by design, but I'd expect the `test` task to run the `jniCompile` before the tests.  Although, I'd even assume that since `compile` depends on `jniCompile` it'd transitively cause `test` to depend on `jniCompile` as well, but apparently that's not the case.

I'd be happy to make this work via a PR, but it's not clear _why_ it's not working in the first place, and my solution might just be a hack (basically, just add another [one of these](https://github.com/joprice/sbt-jni/blob/1918da2633aef7f5a77f79ad38710c505a4b544c/src/main/java/com/github/joprice/Jni.scala#L148)).

**Comment by joprice** [comment]
Yea, if you run `inspect compile` and inspect test:compile`, you see`jniCompile` in the first, but not the second. I'll add a failing test and add another line for test as you suggested. 

I poked around at the sbt source and a few other plugins and found that there is a lot of redundancy to handle this.
