### ISSUE TITLE
Already existing .so lib

### ISSUE THREAD

**Issue by vooolll** [joprice/sbt-jni#18]
Is it possible to use this sbt plugin with already compiled .so library? I have no c/c++ sources but only have .so file which I need to include to my sbt project.

**Comment by joprice** [comment]
I'm not sure I understand the use case. JNI allows java methods marked as `native` to dispatch to cpp methods via JNI-specific c/cpp code (https://www3.ntu.edu.sg/home/ehchua/programming/java/JavaNativeInterface.html). You need to write the native code bindings for those methods. Another library may be linked using normal compiler flags via `jniIncludes`.

**Comment by vooolll** [comment]
@joprice I want to invoke native methods from some library. Currently to add native library I write something like this: System.load('full path to lib')(it complicates configuration), in order to do System.loadLibrary('my lib name') I need to run java with flag  -Djava.library.path=/lib/native_lib.so. I have no idea how to run the same thing with sbt. Can I do something like that with sbt-jni?

**Comment by joprice** [comment]
If you just need to load that library, you don't need this plugin. You can use an sbt setting like this:

https://github.com/joprice/sbt-jni/blob/28b4a36d9d1f668101cc82190626c22296a0ab6b/src/main/scala/com/github/joprice/JniPlugin.scala#L152

However, that assumes that you have a jar with classes with `native` methods and a native library with the matching JNI signatures. Generating those is the intent of this plugin.

**Comment by vooolll** [comment]
@joprice Thanks a lot
